# GitHub Action for generating a contribution graph with a snake eating your contributions
name: Generate Snake

on:
  schedule:
    # Runs every 12 hours
    - cron: "0 */12 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Upgrade to v4 for better reliability/security
      - uses: actions/checkout@v4

      - uses: Platane/snk@v3
        with:
          # Your GitHub username
          github_user_name: Surajvthakur
          
          # The output file for the animation
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push to repo
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add dist/
          
          # Check if there are staged changes. If yes, commit and push.
          if ! git diff --cached --quiet; then
            git commit -m "chore: generate snake"
            git push
          else
            echo "No changes detected in the snake SVGs. Skipping commit."
          fi